create table if not exists public.visitor_logs (
  id bigint generated by default as identity primary key,
  visitor_id text,
  visited_at timestamptz not null default now(),
  local_time text,
  page_path text,
  page_hash text,
  referrer text,
  user_agent text,
  language text,
  timezone text,
  ip text,
  country text,
  region text,
  city text,
  latitude numeric,
  longitude numeric
);

alter table public.visitor_logs enable row level security;

drop policy if exists "Allow public visitor log inserts" on public.visitor_logs;
create policy "Allow public visitor log inserts"
on public.visitor_logs
for insert
to anon
with check (true);

create index if not exists visitor_logs_visited_at_idx
on public.visitor_logs (visited_at desc);

create index if not exists visitor_logs_visitor_id_idx
on public.visitor_logs (visitor_id);
